### ISSUE TITLE
Integration with MEANjs

### ISSUE THREAD

**Issue by timescott** [goodeggs/grunt-mongo-migrations#5]
Hi

I'm looking to incorporate a mongodb migrations framework into my meanjs app. I have read snez's notes  on integrating mongo-migrate https://gist.github.com/snez/ce1248661aefc15cb8d0#file-gistfile1-md. The problem I have with this approach is that it looks like you have to duplicate the mongo connection details. 

Looking around for other frameworks I like the look of grunt-mongo-migrations  which integrates with grunt nicely. What I haven't worked out yet is how to integrate this with meanjs' config. I want to use the NODE_ENV env variable to determine the connection string. So I have the following in my gruntFile.js:

    // Project Configuration
    grunt.initConfig({
    ...
    migrations: {
          path: 'migrations',
          template: grunt.file.read('migrations/_template.js'),
          mongo: '<%= db  %>',
          ext: 'js'
 	}
    });
    
    ...
    
    // A Task for loading the configuration object
    grunt.task.registerTask('loadConfig', 'Task that loads the config into a grunt option.', function() {
    var init = require('./config/init')();
    var config = require('./config/config');
    
    grunt.config.set('applicationJavaScriptFiles', config.assets.js);
    grunt.config.set('applicationCSSFiles', config.assets.css);
    grunt.config.set('db', config.db);
    });
    
    ...
    
    grunt.loadNpmTasks('grunt-mongo-migrations');
    
    ...
    
    // Execute MongoDB migrations
    grunt.registerTask('mongodb-migrate', ['loadConfig', 'migrate:all']);
    
    // List MongoDB migrations
    grunt.registerTask('mongodb-list-migrations', ['loadConfig', 'migrate:pending']);
    
Generating the migrations using grunt-mongo-migrations' 
grunt migrate:generate --name=rename_created_on_to_created_at task works. So I get an empty migration file in /migrations. However if I try and list the migrations using my grunt task I get:

    Tims-MacBook-Pro:run-fit-uk tim$ grunt mongodb-list-migrations
    Running "loadConfig" task
    
     Application loaded using the "development" environment configuration
    
    Running "migrate:pending" task
    Fatal error: Cannot find module 'migrations/20150311075542073_do_something'
    

and if I try to execute the migration also get

    
    Tims-MacBook-Pro:run-fit-uk tim$ grunt mongodb-migrate
    Running "loadConfig" task
    
     Application loaded using the "development" environment configuration
    
    
    Running "migrate:all" task
    Fatal error: Cannot find module 'migrations/20150311075542073_do_something'

The location that is in the output of the task has the correct path.

I'm stumped, any suggestions?

Thanks
Tim

Cross posted from meanjs forum: https://groups.google.com/forum/#!topic/meanjs/FcqSMtcUHxc

**Comment by timescott** [comment]
So the exception is from this line in mongo_migrate.js

    migration = require("" + this.opts.path + "/" + name);

why can't require find my module?

**Comment by bobzoller** [comment]
I think it's the `path` in your migrations config... it should be relative,
eg `./migrations` not just `migrations`.

**Comment by timescott** [comment]
I tried that but doesn't work - the only way I can get it to work is to make it a fully qualified path.

So i've currently got

    path: process.cwd() + '/migrations',

now the problem is that ```describe``` can not be resolved in the generated migrations, I must be missing something...

**Comment by bobzoller** [comment]
I don't see `describe` in our default template
<https://github.com/goodeggs/grunt-mongo-migrations/blob/master/mongo_migrate.coffee#L21>
-- did you add that?  If you're trying to write a test, you must include
the relevant bits to setup your test environment.

**Comment by timescott** [comment]
Yes its not there in your default template but is there in the example on the front page.

So issue closed then if I use a fully qualified path - thanks for your help

**Comment by bobzoller** [comment]
np!
