### ISSUE TITLE
DB credentials in gruntfile?

### ISSUE THREAD

**Issue by eremzeit** [goodeggs/grunt-mongo-migrations#8]
How would one use this library without putting db creds into the gruntfile?  I don't want to do that because the gruntfile gets checked into source control.

Other libraries accomplish this by having config files that are loaded.  These config files can then be added to .gitignore.

**Comment by bobzoller** [comment]
Since the Gruntfile is just code, you can reference `process.env.WHATEVER`
or load it the same way you load your other app settings...

**Comment by eremzeit** [comment]
Ah, makes sense.  Thanks.
